context:
  name: netbird
  version: "0.58.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/netbirdio/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 3d7884fb89e15ed250b6bbfe9d1c059c3c88e25ae79fa1761bb7f02bdc9cf688
    target_directory: src
  - url: https://raw.githubusercontent.com/jmespath/go-jmespath/b89213a6ec69212a244ef0d07d893bef7f2d9091/LICENSE
    sha256: cfc7749b96f63bd31c3c42b5c471bf756814053e847c10f3eb003417bc523d30
    file_name: LICENSE-jmespath

build:
  number: 0
  script:
    - cd src
    - cd client
    - go-licenses save . --save_path ../../library_licenses --ignore github.com/jmespath/go-jmespath
    - if: unix
      then: go build -v -o $PREFIX/bin/netbird -ldflags="-s -w"
      else: go build -v -o %LIBRARY_BIN%\netbird.exe -ldflags="-s"

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script: netbird -h
  - package_contents:
      bin:
        - netbird

about:
  homepage: https://github.com/netbirdio/netbird
  summary: Connect your devices into a secure WireGuard®-based overlay network with SSO, MFA and granular access controls.
  license: BSD-3-Clause
  license_file:
    - src/LICENSE
    - library_licenses/
    - LICENSE-jmespath
  repository: https://github.com/netbirdio/netbird

extra:
  recipe-maintainers:
    - xhochy
