context:
  name: netbird
  version: "0.74.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/netbirdio/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 8d5904ef0aa5aa6cb9cb1479fa257bbe1b4755327393fa9c153b115477ec25cb
    target_directory: src
  - url: https://raw.githubusercontent.com/jmespath/go-jmespath/b89213a6ec69212a244ef0d07d893bef7f2d9091/LICENSE
    sha256: cfc7749b96f63bd31c3c42b5c471bf756814053e847c10f3eb003417bc523d30
    file_name: LICENSE-jmespath
  - url: https://raw.githubusercontent.com/jackpal/go-nat-pmp/e04deda90d5683d6e375732740814a89eea7bafd/LICENSE
    sha256: 1596ea320a3d9e5180576b2c6dd28aa34b9edcef27693fcd0474e24bda3fdcab
    file_name: LICENSE-nat-pmp

build:
  number: 0
  script:
    - cd src
    - cd client
    - go-licenses save . --save_path ../../library_licenses --ignore github.com/jmespath/go-jmespath --ignore github.com/jackpal/go-nat-pmp
    - if: unix
      then: go build -v -o $PREFIX/bin/netbird -ldflags="-s -w"
      else: go build -v -o %LIBRARY_BIN%\netbird.exe -ldflags="-s"

requirements:
  build:
    - ${{ compiler("go-nocgo") }} 1.25.*
    - go-licenses

tests:
  - script: netbird -h
  - package_contents:
      bin:
        - netbird

about:
  homepage: https://github.com/netbirdio/netbird
  summary: Connect your devices into a secure WireGuard®-based overlay network with SSO, MFA and granular access controls.
  license: BSD-3-Clause
  license_file:
    - src/LICENSE
    - library_licenses/
    - LICENSE-jmespath
  repository: https://github.com/netbirdio/netbird

extra:
  recipe-maintainers:
    - xhochy
